# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6675c064a8283789ac5e9ba3071dc052a0279e397253afa083b9c9194b2f3089deb215a7a935de1998f01e2f1aec33bd51e8cb45759c44712e9fe03a9f029aa8

test:
  secret_key_base: 917b8e0353b3eeee80cfae673ce2d43bf25594ae8b935a075d2ae8f43b44d6584f5280911b6845265000e487d3299fe349c3d06bb0bb71bd3428bfb85e43c3c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
